import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@clerk/nextjs/server'
import { supabase } from '@/lib/supabase'
import PDFDocument from 'pdfkit'
import Anthropic from '@anthropic-ai/sdk'
import { PLATFORM_LABELS, type Platform } from '@/lib/types'

const schema = z.object({
  days: z.number().int().min(1).max(365).optional().default(30),
  profileId: z.string().uuid().optional(),
})

const anthropic = new Anthropic()

export async function POST(req: NextRequest) {
  const { userId, orgId } = await auth()
  if (!userId || !orgId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const parsed = schema.safeParse(await req.json())
  if (!parsed.success) return NextResponse.json({ error: 'Invalid input' }, { status: 400 })
  const { days, profileId } = parsed.data
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()

  // Fetch data
  const { data: profiles } = await supabase.from('profiles').select('id, name').eq('org_id', orgId)
  const profileIds = profileId
    ? [profileId]
    : (profiles ?? []).map((p) => p.id)

  const profileNames = (profiles ?? []).reduce<Record<string, string>>((acc, p) => {
    acc[p.id] = p.name
    return acc
  }, {})

  const { data: posts } = profileIds.length
    ? await supabase.from('posts').select('id, content, platforms, status, created_at, profile_id').in('profile_id', profileIds).gte('created_at', since).order('created_at', { ascending: false }).limit(200)
    : { data: [] }

  const postIds = (posts ?? []).map((p) => p.id)
  const { data: results } = postIds.length
    ? await supabase.from('post_results').select('post_id, platform, status').in('post_id', postIds)
    : { data: [] }

  const allPosts = posts ?? []
  const allResults = results ?? []
  const totalPosts = allPosts.length
  const successCount = allResults.filter((r) => r.status === 'success').length
  const successRate = allResults.length > 0 ? Math.round((successCount / allResults.length) * 100) : 0
  const activePlatforms = [...new Set(allResults.map((r) => r.platform))]

  // Per-platform breakdown
  const platformStats = activePlatforms.map((p) => ({
    platform: p,
    label: PLATFORM_LABELS[p as Platform]?.split(' ')[0] ?? p,
    success: allResults.filter((r) => r.platform === p && r.status === 'success').length,
    failed: allResults.filter((r) => r.platform === p && r.status === 'failed').length,
  }))

  // Top posts
  const topPosts = allPosts
    .map((post) => {
      const postResults = allResults.filter((r) => r.post_id === post.id)
      return { ...post, successCount: postResults.filter((r) => r.status === 'success').length }
    })
    .sort((a, b) => b.successCount - a.successCount)
    .slice(0, 5)

  // Claude recommendations
  let recommendations = 'Continue posting consistently and engaging with your audience.'
  try {
    const msg = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 300,
      messages: [{
        role: 'user',
        content: `Based on this social media data, provide 3 brief actionable recommendations (1-2 sentences each).

Total posts: ${totalPosts}
Success rate: ${successRate}%
Active platforms: ${activePlatforms.map((p) => PLATFORM_LABELS[p as Platform] ?? p).join(', ')}
Date range: last ${days} days

Write ONLY the 3 numbered recommendations. Be specific and actionable.`,
      }],
    })
    recommendations = (msg.content[0] as { type: string; text: string }).text.trim()
  } catch {
    // Use fallback
  }

  // Generate PDF
  const doc = new PDFDocument({ margin: 50, size: 'A4' })
  const chunks: Buffer[] = []
  doc.on('data', (chunk: Buffer) => chunks.push(chunk))

  await new Promise<void>((resolve) => {
    doc.on('end', resolve)

    const dateRangeStr = `Last ${days} days · ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`

    // ─── Cover page ───
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0a0a0a')
    doc.fill('#ffffff').fontSize(32).font('Helvetica-Bold').text('Social Media Report', 50, 200)
    doc.fontSize(14).font('Helvetica').text(profileId ? (profileNames[profileId] ?? 'All Profiles') : 'All Profiles', 50, 250)
    doc.fontSize(12).fill('#999999').text(dateRangeStr, 50, 280)
    doc.fill('#ffffff').fontSize(10).text('Generated by Fanout', 50, doc.page.height - 80)

    doc.addPage()

    // ─── Executive Summary ───
    doc.fill('#000000').fontSize(20).font('Helvetica-Bold').text('Executive Summary', 50, 50)
    doc.moveDown(0.5)
    doc.fontSize(11).font('Helvetica')

    const summaryItems = [
      ['Total Posts', totalPosts.toString()],
      ['Success Rate', `${successRate}%`],
      ['Active Platforms', activePlatforms.length.toString()],
      ['Profiles', (profiles ?? []).length.toString()],
    ]

    let y = 110
    summaryItems.forEach(([label, value]) => {
      doc.rect(50, y, 220, 60).fill('#f9fafb').stroke('#e5e7eb')
      doc.fill('#6b7280').fontSize(9).text(label, 60, y + 10)
      doc.fill('#111827').fontSize(22).font('Helvetica-Bold').text(value, 60, y + 24)
      y += 75
    })

    doc.addPage()

    // ─── Platform Performance ───
    doc.fill('#000000').fontSize(20).font('Helvetica-Bold').text('Platform Performance', 50, 50)
    doc.moveDown(1)

    if (platformStats.length === 0) {
      doc.fontSize(11).font('Helvetica').fill('#6b7280').text('No platform data available for this period.', 50, 100)
    } else {
      // Table header
      doc.rect(50, 95, 495, 25).fill('#111827')
      doc.fill('#ffffff').fontSize(9).font('Helvetica-Bold')
      doc.text('Platform', 60, 103)
      doc.text('Success', 250, 103)
      doc.text('Failed', 340, 103)
      doc.text('Success Rate', 430, 103)

      let tableY = 120
      platformStats.forEach((p, i) => {
        const total = p.success + p.failed
        const rate = total > 0 ? Math.round((p.success / total) * 100) : 0
        doc.rect(50, tableY, 495, 25).fill(i % 2 === 0 ? '#f9fafb' : '#ffffff').stroke('#e5e7eb')
        doc.fill('#111827').fontSize(9).font('Helvetica')
        doc.text(p.label, 60, tableY + 8)
        doc.text(p.success.toString(), 250, tableY + 8)
        doc.text(p.failed.toString(), 340, tableY + 8)
        doc.text(`${rate}%`, 430, tableY + 8)
        tableY += 25
      })
    }

    doc.addPage()

    // ─── Top Posts ───
    doc.fill('#000000').fontSize(20).font('Helvetica-Bold').text('Top Performing Posts', 50, 50)
    doc.moveDown(1)

    topPosts.forEach((post, i) => {
      const contentPreview = (post.content as string).slice(0, 120) + ((post.content as string).length > 120 ? '…' : '')
      const platforms = (post.platforms as string[]).map((p) => PLATFORM_LABELS[p as Platform]?.split(' ')[0] ?? p).join(', ')
      const boxY = 100 + i * 80

      doc.rect(50, boxY, 495, 70).fill('#f9fafb').stroke('#e5e7eb')
      doc.fill('#6b7280').fontSize(9).font('Helvetica-Bold').text(`#${i + 1}`, 60, boxY + 10)
      doc.fill('#111827').fontSize(10).font('Helvetica').text(contentPreview, 80, boxY + 10, { width: 380 })
      doc.fill('#6b7280').fontSize(8).text(`${platforms} · ${post.successCount} successful distributions`, 80, boxY + 52)
    })

    doc.addPage()

    // ─── Recommendations ───
    doc.fill('#000000').fontSize(20).font('Helvetica-Bold').text('Recommendations', 50, 50)
    doc.moveDown(1)
    doc.rect(50, 95, 495, 4).fill('#111827')
    doc.moveDown(0.5)
    doc.fill('#374151').fontSize(11).font('Helvetica').text(recommendations, 50, 115, { width: 495, lineGap: 4 })

    // Footer on last page
    doc.fill('#9ca3af').fontSize(8).text(`Generated by Fanout · ${new Date().toISOString()}`, 50, doc.page.height - 60)

    doc.end()
  })

  const pdfBuffer = Buffer.concat(chunks)
  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="fanout-report-${days}d.pdf"`,
    },
  })
}
